### ISSUE TITLE
Disable import folding

### ISSUE THREAD

**Issue by alexhayes** [devkanro/intellij-protobuf-plugin#100]
I have all folding turned off but still when I open a file it folds imports. Is there a way to turn this off?

<img width="451" alt="image" src="https://user-images.githubusercontent.com/142916/167728462-a24911a2-fe4d-486a-974c-296535136ba4.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/142916/167728493-680b1dda-4c68-4793-bd32-2d248b00a4e0.png">

**Comment by devkanro** [comment]
I will use the common folding config for protobuf folding in next version, it will release with #102 maybe.

**Comment by alexhayes** [comment]
Thankyou! 🎉

**Comment by devkanro** [comment]
A open test for next version is active now.
You can download it and help us to test in #102.

**Comment by devkanro** [comment]
Fixed by release [v1.6.0](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.6.0)
