### ISSUE TITLE
Support JetBrains HTTP Client

### ISSUE THREAD

**Issue by BorzdeG** [devkanro/intellij-protobuf-plugin#102]
Since the plugin conflicts with the bundle plugin from JetBrains, the ability to work with the client to generate gRPC requests also disappears.

I would like this plugin to provide the ability to perform gRPC requests to the server...

https://blog.jetbrains.com/idea/2021/10/intellij-idea-2021-3-eap-6-enhanced-http-client-kotlin-support-for-cdi-and-more/#gRPC_requests_in_the_HTTP_client

**Comment by devkanro** [comment]
Some update here, the HTTP client is not open source plugin, I am trying to create extension for it.

The first version just support the local proto file, the reflection server will be support in next major version.

I am focus on the auto complete for GRPC request line, now it support the json body and method name.

But the request executing is not complete now.

**Comment by devkanro** [comment]
Some update here, I have completed the basic feature of HTTP client.
Before I release it, I need more tests for it.
You can download it and install it by hand to join and help my test.

[IntelliJ Protobuf Language Plugin-1.6.0.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/8852795/IntelliJ.Protobuf.Language.Plugin-1.6.0.zip)

**Comment by devkanro** [comment]
Fixed by release [v1.6.0](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.6.0)
