### ISSUE TITLE
更新插件到1.6.0版本后设置页面无法打开.

### ISSUE THREAD

**Issue by tangqiu0205** [devkanro/intellij-protobuf-plugin#108]
GoLand 2022.1.2 
从这里下载的[Releases](https://github.com/devkanro/intellij-protobuf-plugin/releases)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/37826977/173043158-aa18f2bf-2b3a-43e0-9488-525ebd528a61.png">

**Comment by devkanro** [comment]
IDEA 版本呢，是从哪里下载的 1.6.0 版本？

**Comment by devkanro** [comment]
<img width="1012" alt="截屏2022-06-10 下午6 30 18" src="https://user-images.githubusercontent.com/9367842/173046938-aed576b6-4f7a-43e7-b0be-cdee8e29384d.png">
<img width="564" alt="截屏2022-06-10 下午6 30 42" src="https://user-images.githubusercontent.com/9367842/173046987-6407f3ac-c34b-470a-968a-6e824dc813b2.png">
2022.1 好像没啥问题

**Comment by devkanro** [comment]
2022.1.2 好像有点 bug，好像之前的版本也打不开，我没发版之前自己升级了一下，发现很多东西都用不了了，我就回滚了

**Comment by tangqiu0205** [comment]
我现在还不好回退, 先禁用掉, 等你或者JB官方解决我再用吧.

**Comment by devkanro** [comment]
<img width="1094" alt="截屏2022-06-10 下午6 55 41" src="https://user-images.githubusercontent.com/9367842/173050646-1d3a0e5b-0d43-4de5-8e7d-d13052c9561d.png">
我跑了一下 IU-2022.1.2 也没啥问题

**Comment by tangqiu0205** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/37826977/173051871-9aa0729a-43d0-46e3-9d36-75c6d431dae6.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/37826977/173051951-597cc9be-2015-4c1e-82be-a0236b4d7b26.png">

Idea 确实没问题, goland则打不开.

**Comment by devkanro** [comment]
我找到问题了，是因为设置页面用了 IDEA 里面 Java 插件的一个代码，等会儿我就发布一下 1.6.10，然后还找到了一些别的地方这样的错误用法。
等 JB 更新 gradle 插件支持多模块，我就重构一下插件结构，现在我是针对 IU 开发，所以开发过程中总是会自动导入一些莫名其妙的工具方法。
