### ISSUE TITLE
Plugin is not compatible with GoLand 2022.2 EAP

### ISSUE THREAD

**Issue by Atomzwieback** [devkanro/intellij-protobuf-plugin#111]
Hi,

great plugin and thx for the work, but i would like to report that the plugin not works for the mentioned version. Its the own plugin that not works atm. May you could release a version?

regars

**Comment by devkanro** [comment]
The api of Http Client plugin is unstable in 2022.2 EAP, it changed in minor version, I will wait for it be more stable.

**Comment by BorzdeG** [comment]
@devkanro Can upload the plugin to the [EAP](https://plugins.jetbrains.com/plugin/16422-protobuf/versions/eap) channel?

**Comment by devkanro** [comment]
@BorzdeG 
The 1.6.20-EAP can't pass the plugin verifier, so I can't publish to EAP channel.

But I got some notice JetBrains will create first RC version for 2022.2 in 07/19，I will try to update my plugin target to 2022.2 RC soon.

**Comment by devkanro** [comment]
@BorzdeG @Atomzwieback 
Just try target to latest 222.3345.16-EAP, but the HTTP Client plugin has no compatible version for it (the latest version is target to 222.3244)

We still need to wait for it.

**Comment by devkanro** [comment]
Fixed by [1.6.20-EAP](https://plugins.jetbrains.com/plugin/16422-protobuf/versions/EAP/195039)

**Comment by BorzdeG** [comment]
The plugin was downloaded manually from https://plugins.jetbrains.com/plugin/16422-protobuf/versions/eap because the repository could [not be connected](https://youtrack.jetbrains.com/issue/IDEA-297917/Unable-to-connect-EAP-plugin-repository)

At the same time, the plugin, which was attached here in the thread, was installed correctly

<img width="378" alt="image" src="https://user-images.githubusercontent.com/2332528/178912779-70a4ef7e-b0f3-4ac0-9890-810c311f9424.png">

**Comment by devkanro** [comment]
Ummm...The plugin current just compatible with BETA version (IDEA 222.3345.*)

The nightly version which you used currently can't not be used in plugin dev, so I can't create a compatible version for it.

<img width="552" alt="截屏2022-07-14 下午2 26 25" src="https://user-images.githubusercontent.com/9367842/178915038-40ee5ec8-91d1-42a6-bcf2-a6e6898cce78.png">

**Comment by BorzdeG** [comment]
But the plugin, which is archived here above, installs perfectly on the same nightly version.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2332528/178916396-35a43f1c-1c12-4a01-a9d9-56969479fb19.png">

**Comment by devkanro** [comment]
<img width="545" alt="1657780548" src="https://user-images.githubusercontent.com/9367842/178916826-25951540-62eb-4a61-be7a-c6ca68d9022d.png">
And maybe you should use the beta version with eap repository.

**Comment by BorzdeG** [comment]
Yes, in beta the repository is connected correctly

**Comment by devkanro** [comment]
The version in this thread is build by manually, I make it with compatibility range 222.* because I don't need pass the plugin verifier.

The version in eap repository is build by CI the compatibility range is 222.3345.* because it just can pass the 222.3345.* verifier.

**Comment by devkanro** [comment]
If you need it I can build a version for you, it has 222.3345-222.* compatibility range, and with new UI icons.

**Comment by BorzdeG** [comment]
Thanks, but it's not critical :) I'll use the Beta version instead of the nightly build

**Comment by devkanro** [comment]
[IntelliJ Protobuf Language Plugin-1.6.20-EAP.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/9109225/IntelliJ.Protobuf.Language.Plugin-1.6.20-EAP.zip)

Use this version if you need the new UI icons.

**Comment by devkanro** [comment]
I will open a issue for listing my manual build version, it can bypass the plugin verifier, it will useful to help users which use the early early access version.

**Comment by devkanro** [comment]
I created a discuss for listing my manual build version, [Check it here](https://github.com/devkanro/intellij-protobuf-plugin/discussions/115).

[Read me](https://github.com/devkanro/intellij-protobuf-plugin/discussions/114) before you use those versions.
