### ISSUE TITLE
After installing the plugin the IDE hangs on startup.

### ISSUE THREAD

**Issue by richburdon** [devkanro/intellij-protobuf-plugin#126]
Webstorm 2022.2 hangs after installing this plugin. Now unable to revert or use Webstorm.

**Comment by devkanro** [comment]
Can you describe the problem you're having in more detail?

What's your IDEA version? Plugin version? The screenshot?

What's your project type? Go? Maven? Gradle?

Waht's your protobuf plugin settings?

**Comment by richburdon** [comment]
Hi, first, thanks for the plugin!

I saw the warning about this being incompatible with the default plugin. The problem was you have to first remove the default plugin, restart, then install your plugin. If you get this wrong Webstorm freezes and you have to manually find and delete the default plugin before you can get WS to start.

It wasn't obvious to me how to do this, so I had to go surfing to find the right locations. I'm currently using Toolbox, so it was the second filepath. It might be helpful to put these instructions in your plugin description?

~/Library/Application Support/JetBrains/Webstorm2022.2/plugins/protoeditor (if installed manually)
~/Library/Application Support/Toolbox/apps/WebStorm/.../WebStorm.app.plugins/protoeditor (if using Toolbox)

The second problem is Webstorm seems to re-install (and activate) it's default plugin. Perhaps that's because I deleted it, but I couldn't figure out how else to disable it once Webstorm has frozen. I guess I should have renamed the file, started-up, tried to disable it, then rename it back.

IDE: Webstorm
Project: Node.js

Details below:

WebStorm 2022.2.3
Build #WS-222.4345.14, built on October 5, 2022
Licensed to Rich Burdon
Subscription is active until February 7, 2023.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 20
Metal Rendering is ON
Non-Bundled Plugins:
    wallaby.js (1.0.253)
    ru.adelf.idea.dotenv (2022.2)
    org.toml.lang (222.4345.14)
    org.intellij.RegexpTester (1.0.8)
    com.intellij.plugin.applescript (0.121)
    io.kanro.idea.plugin.protobuf (1.6.22)
    com.github.copilot (1.1.33.1980)
    YAML/Ansible support (0.11.2)
    mdx.js (222.4345.14)
    izhangzhihao.rainbow.brackets (6.26)
    com.github.iguissouma.nxconsole (0.50.0)
    CMD Support (1.0.5)

**Comment by devkanro** [comment]
Thanks for your information, I will pin this issue in my issues page.

**Comment by devkanro** [comment]
Cloud you update your rating in jetbrains plugin comment?
