### ISSUE TITLE
Not compatible with  IDEA 2022.3

### ISSUE THREAD

**Issue by marcindabrowski** [devkanro/intellij-protobuf-plugin#141]
The current version requires building 222.* or earlier.
Please upgrade it

**Comment by devkanro** [comment]
Already released, wait for JetBrains' review and [approval] 

Or you can download it from [release page](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.6.30)

**Comment by marcindabrowski** [comment]
Thanks
