### ISSUE TITLE
I know you'll be quick to update to Golang 2012.2 EAP

### ISSUE THREAD

**Issue by zzwx** [devkanro/intellij-protobuf-plugin#17]
![goland64_V0volFfOlj](https://user-images.githubusercontent.com/8169082/119983232-e056a200-bf8d-11eb-80db-e92feb552cd3.png)

**Comment by devkanro** [comment]
Close by Release [1.4-EAP](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4-EAP)

**Comment by zzwx** [comment]
Amazing! Thank you so much!

**Comment by devkanro** [comment]
@zzwx 
I found the [Protocol Buffers](https://plugins.jetbrains.com/plugin/14004-protocol-buffers)(original: Protocol Buffers Editor) has been converted to JetBrains Offical Plugin which will be bundled in Intellij Release(after 212.3116.45).

And the source code has moved to [JetBrains/intellij-plugins](https://github.com/JetBrains/intellij-plugins/tree/master/protobuf), if you install my plugin in 212.3116.45, you will get the error message with loading plugin.

After the 2021.2 release, if you want to use my plugin continually, you should disable both of official protobuf and grpc plugin, then enable or install my plugin.

This incident does have a major impact on the popularity of my plugin. But as I said I made this plugin for my team, if we still use the Protobuf/GRPC, I will keep maintain this plugin.

**Comment by zzwx** [comment]
They make life complicated! I wonder if your plugin can automatically offer to disable theirs

**Comment by devkanro** [comment]
There is no way to disable a plugin from another plugin, you must disable them manually.

**Comment by zzwx** [comment]
As a recommendation may be? Like a reminder. I wonder if they do warn about a possible conflict.

Are you feeling that it's not worth to continue developing?

**Comment by devkanro** [comment]
> As a recommendation may be? Like a reminder. I wonder if they do warn about a possible conflict.    

Yes, maybe I can create a reminder before plugin loaded.

> Are you feeling that it's not worth to continue developing?

No, as I said I made this plugin for my team, if we still use the Protobuf/GRPC and the official plugin can't cover our demands, I will keep maintain this plugin.

**Comment by zzwx** [comment]
Thank you for it! It’s really helping me too

**Comment by devkanro** [comment]
@zzwx 
I am planning to provide more and smarter customization features for protobuf on the go project.
In my development process, I am looking for some go users to participate in my plug-in preview project.
Check #37 for the details.
