### ISSUE TITLE
Plugin not compatible with 232.* builds

### ISSUE THREAD

**Issue by davidbauer99** [devkanro/intellij-protobuf-plugin#181]
Not sure about Intellij, but the latest RubyMine 2023.2 EAP has a build number of `232.5150.113`. The current comaptibility range for the [latest release of the Protobuf plugin](https://plugins.jetbrains.com/plugin/16422-protobuf/versions/stable/321456) is `231—231.*`.

For now I'm just not using the EAP to continue using this plugin, but I assume that an eventual 2023.2 release would similarly be incompatible.

**Comment by devkanro** [comment]
When version 232 is released, I'll check for compatibility and target the plugin to 232.

**Comment by Fengxq2014** [comment]
IntelliJ IDEA 2023.2 Is Out! July 26, 2023

**Comment by devkanro** [comment]
Updating for it

**Comment by devkanro** [comment]
Plz check the #189 
I will release it in next two or three days

**Comment by devkanro** [comment]
Fixed by v1.7.13
