### ISSUE TITLE
Plugin not compatible with 2023.2

### ISSUE THREAD

**Issue by craigday** [devkanro/intellij-protobuf-plugin#190]
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1

<img width="271" alt="Screenshot of IntelliJ IDEA (2-8-2023, 2-49-02 pm)" src="https://github.com/devkanro/intellij-protobuf-plugin/assets/723789/6a9c7151-096d-4147-94fe-077d85bef19c">

**Comment by devkanro** [comment]
ref to #181

**Comment by devkanro** [comment]
Plz check the update for 1.7.13/1.7.14
