### ISSUE TITLE
设置protobuf路径，但在proto文件中显示not found

### ISSUE THREAD

**Issue by younglifestyle** [devkanro/intellij-protobuf-plugin#191]
1.7.13版本

![image](https://github.com/devkanro/intellij-protobuf-plugin/assets/19261307/205a5024-d252-4564-aca4-f7f0bb5d942a)

![image](https://github.com/devkanro/intellij-protobuf-plugin/assets/19261307/ac576d1f-4c31-4756-b605-a8c3d583076b)

**Comment by devkanro** [comment]
理论上来讲，你是不需要包含这个路径的，我自带了 google/protobuf/*.proto

你是什么语言的项目？Java？Go？用的什么项目结构？Maven？Gradle？GoMod？

**Comment by younglifestyle** [comment]
> 理论上来讲，你是不需要包含这个路径的，我自带了 google/protobuf/*.proto
> 
> 你是什么语言的项目？Java？Go？用的什么项目结构？Maven？Gradle？GoMod？

Goland，GoMod项目。
我也很疑惑，升级了Goland 2023.2之后出现的问题（当时插件还是1.7.12，不兼容的状态），后面更新了插件版本1.7.13就找不到了。我尝试回退回2023.1.4还是同样找不到。
再之后，我就重新启用了官方的protobuf插件，可以找到，再重新启用回插件，发现就OK了。

**Comment by devkanro** [comment]
官方的 protobuf 插件和我的插件有冲突，不能启用
