### ISSUE TITLE
Navigation from stub to the schema

### ISSUE THREAD

**Issue by fan-tom** [devkanro/intellij-protobuf-plugin#193]
Currently it is possible to go from gRPC method/service implementation to the corresponding schema definition, and from the schema definition to the stub (client) calls.
But it is impossible to navigate from client stub to the schema, which is very useful to find the server-side implementation for given client-side gRPC invocation

**Comment by devkanro** [comment]
Thank you for your contribution! I will release the next version as soon as possible
