### ISSUE TITLE
Support Idea 2024.1 Build 241.14494.240, Mar. 28

### ISSUE THREAD

**Issue by boan-anbo** [devkanro/intellij-protobuf-plugin#245]
Hi thanks for the awesome plugin! It has been indispensable. But it has been marked incompatible by the latest Idea edition.

**Comment by devkanro** [comment]
See #239 , I will release the 1.7.60 soon next week, before it releases you can use the EAP version

**Comment by boan-anbo** [comment]
Many thanks! Didnt realize there's EAP.

**Comment by devkanro** [comment]
Closed by Release 1.7.60
