### ISSUE TITLE
`~` is not supported in external import roots

### ISSUE THREAD

**Issue by maratori** [devkanro/intellij-protobuf-plugin#252]
We use `bazel` in our project. It puts external `.proto` files in the directory containing `~`, for example
```
/private/var/tmp/_bazel_marat-reymers/9eb28da2e14c36618091dce70be2b929/external/com_google_googleapis~
```
The plugin can't resolve imports from that directory.

As a workaround, I've created a symlink and used it in the settings.

**Comment by devkanro** [comment]
Can your provide a example project for it?

**Comment by maratori** [comment]
Here is the repository with the example https://github.com/maratori/protobuf-plugin-bug

**Comment by devkanro** [comment]
This is a IntelliJ issue, IntelliJ ignore all files and folders which ends with ~

You can change this behavoir by  **Settings | Editor | File Types | Ignore files and folders**

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206260659-IDEA-10-hides-directories-with-tilde

**Comment by devkanro** [comment]
![image](https://github.com/devkanro/intellij-protobuf-plugin/assets/9367842/7529f47c-d056-48d5-871a-a74d528ddaf3)
