### ISSUE TITLE
Built-in option 'go_package' not found

### ISSUE THREAD

**Issue by ilovesusu** [devkanro/intellij-protobuf-plugin#28]
```proto
syntax = "proto3";

package ecommerce;

option go_package = "proto";

service ProductInfo {
    rpc AddProject(Product) returns  (ProductId);
    rpc GetProduct(ProductId) returns (Product);
}

message ProductId {
    string id = 1;
    string name = 2;
    string description = 3;
    float price = 4;
}

message Product {
    string value = 1;
}
```
![image](https://user-images.githubusercontent.com/12681726/124714070-e1d39c80-df33-11eb-9454-dc2352b5b00f.png)

**Comment by devkanro** [comment]
The plugin will not provide the well-known protos, and the plugin will scan all depented libraries for the java project.

To make the plugin work with go project, you need to download google's well-known protos to a folder, and mark this folder as import root in `Settings` > `Language $ Frameworks` > `Protobuf`.

If you can't find google's built-in protos, download it from [here](https://github.com/devkanro/intellij-protobuf-plugin/files/6775100/proto.zip).

See #4 for the details.

**Comment by ilovesusu** [comment]
thx

**Comment by devkanro** [comment]
@ilovesusu 
I am planning to provide more and smarter customization features for protobuf on the go project.
In my development process, I am looking for some go users to participate in my plug-in preview project.
Check #37 for the details.
