### ISSUE TITLE
plugin says it's incompatible with current version of CLion, but version is OK according to plugin's requirements

### ISSUE THREAD

**Issue by senatus** [devkanro/intellij-protobuf-plugin#34]
<img width="735" alt="image1" src="https://user-images.githubusercontent.com/20600117/127449071-0ff47746-ccc1-445e-a6d6-2bbf8ad7f72b.png">
CL-212.4746.93, JRE 11.0.11+9-b1504.13x64 JetBrains s.r.o., OS Mac OS X(aarch64) v11.4, screens 2880.0x1800.0; Retina

I've created an issue on youtrack (https://youtrack.jetbrains.com/issue/CPP-26003). They say it's on your side.

**Comment by devkanro** [comment]
Use the [1.4.1-EAP](https://plugins.jetbrains.com/plugin/16422-protobuf/versions/EAP/126218) for IDEA Platform 212 or later.

See #17

**Comment by devkanro** [comment]
You can install it with the EAP channel or download the zip package in [release](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.1-EAP).

I will release v1.4.0 this week, it supports the CLion 212

**Comment by senatus** [comment]
@devkanro thanks. I'll try to use it.
Was confused a little because of the message. Because 212.* is older than 211.*

**Comment by devkanro** [comment]
A note for you, JetBrains adopted another plugin as the [official protobuf plugin](https://github.com/jvolkman/intellij-protobuf-editor) in 2021.2.

And the source code has moved to [JetBrains/intellij-plugins](https://github.com/JetBrains/intellij-plugins/tree/master/protobuf), if you install my plugin in 212 or later, you will get the error message with loading plugin.

After the 2021.2 release, if you want to use my plugin continually, you should disable both of official protobuf and grpc plugin, then enable or install my plugin.

**Comment by senatus** [comment]
@devkanro yes, I know the problem. Already know what to do. But thanks for your care. Have a nice day.
