### ISSUE TITLE
plugin not support CLion 2021.2

### ISSUE THREAD

**Issue by gcc-tan** [devkanro/intellij-protobuf-plugin#35]
![image](https://user-images.githubusercontent.com/19588252/127465097-11eddf7d-e3ea-4c86-b59d-d16663da4429.png)

![image](https://user-images.githubusercontent.com/19588252/127465542-482a6948-e46b-4fd1-a6f4-2cc1d12ec385.png)

**Comment by devkanro** [comment]
See discussion in #34 

I have released 1.4.0, it will be listed in Jetbains Plugins Repository in 2 days.

A note for you too, JetBrains adopted another plugin as the [official protobuf plugin](https://github.com/jvolkman/intellij-protobuf-editor) in 2021.2.

And the source code has moved to [JetBrains/intellij-plugins](https://github.com/JetBrains/intellij-plugins/tree/master/protobuf), if you install my plugin in 212 or later, you will get the error message with loading plugin.

After the 2021.2 release, if you want to use my plugin continually, you should disable both of official protobuf and grpc plugin, then enable or install my plugin.

**Comment by gcc-tan** [comment]
Thanks for the reply，I should search issues first
