### ISSUE TITLE
Imports not found

### ISSUE THREAD

**Issue by RicardormDev** [devkanro/intellij-protobuf-plugin#38]
Imports are not recognized by the editor. They compile correctly. 
![imagen](https://user-images.githubusercontent.com/8129679/128556545-99cfe8db-f158-4a0b-8e43-8c380cf540a7.png)

**Comment by devkanro** [comment]
Please provide more information about your usage, like IDEA version, plugin version, your project language, build tool, project struct.

Reference: #4

**Comment by RicardormDev** [comment]
Sure, thanks.

**Comment by devkanro** [comment]
No more information, I will close it, you can reopen it if you have any question
