### ISSUE TITLE
Plugin uses proprietary resources copied from IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by jreznot** [devkanro/intellij-protobuf-plugin#39]
Hi,
Since revision c218d87f844c18aba52b02053f50c5e1ed7c0fcd the repository contains two files:

- `src/main/resources/io/kanro/idea/plugin/protobuf/icon/procedure.svg`
- `src/main/resources/io/kanro/idea/plugin/protobuf/icon/procedure_dark.svg`

These files are copies of files from JetBrains gRPC plugin. This plugin is not OSS and you may not copy and redistribute its parts in your plugin. It is the violation of JetBrains copyright.

Diff: (left is the file from this repository, right is the file from JetBrains gRPC plugin)

![image](https://user-images.githubusercontent.com/1066152/128671063-77686614-7b8a-4812-885d-282a62cf757d.png)

Please remove the copied images and do not use resources from JetBrains plugins if they are not OSS (even then resources may be provided under different license than sources).

**Comment by devkanro** [comment]
Sorry for that, I will remove it soon.

The endpoint feature is not included in the current version 1.4.1, I will redesign this icon before 1.4.2 released.
