### ISSUE TITLE
Built-in option 'go_package' not found

### ISSUE THREAD

**Issue by kekek** [devkanro/intellij-protobuf-plugin#41]
I don't konw how to set path in goland to fix the question "Built-in option 'go_package' not found". So I put the project in the address https://github.com/kekek/ent

My local environment  is ： 
```
GoLand 2021.2
Build #GO-212.4746.93, built on July 27, 2021
Subscription is active until January 20, 2022.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.12.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, suggest.all.run.configurations.from.context=true, ide.completion.variant.limit=500, ide.balloon.shadow.size=0
Non-Bundled Plugins: YAML/Ansible support (0.11.2), com.mallowigi.idea (16.0), de.netnexus.camelcaseplugin (3.0.8), net.sjrx.intellij.plugins.systemdunitfiles (0.3.3), mobi.hsz.idea.gitignore (4.2.0), com.intellij.kubernetes (212.4746.57), cn.yiiguxing.plugin.translate (3.1.1), io.kanro.idea.plugin.protobuf (1.4.2), ru.adelf.idea.dotenv (2021.3.0.212)

```

bellow is the protobuf path I set in my goland
![path setting in the editor  for protobuf](https://user-images.githubusercontent.com/4726765/129344362-9a2ddf5e-83c6-4533-a125-8f3c6f7ecf31.png)

But it still doesn't work 

![problems report by editor](https://user-images.githubusercontent.com/4726765/129344662-b4337ac8-47b5-406a-ad09-e70ec7329062.png)

Is there a detailed description to tell how the plugin worked?  How to set import path？

**Comment by devkanro** [comment]
Add `third-party` to your protobuf import path like this:
![image](https://user-images.githubusercontent.com/9367842/129348187-01ec70f7-915c-498a-a148-39b4a3266874.png)

I will auto-detect the go path in 1.4.2, but I found it does not work with go mod, maybe fix it in next version

**Comment by devkanro** [comment]
And after you add `third-party` to import path, you should use the relative path based on `third-party` in your `import` statement.

```protobuf
import "third-party/ent/options/opts.proto"; // Not do this
import "ent/options/opts.proto"; // Do this
```

**Comment by kekek** [comment]
> And after you add `third-party` to import path, you should use the relative path based on `third-party` in your `import` statement.
> 
> ```proto
> import "third-party/ent/options/opts.proto"; // Not do this
> import "ent/options/opts.proto"; // Do this
> ```

Think you for you reply， I did what you told me and it worked well。

Another question, there are some extensions, such as third-party/google, many projects will use it, I want to put it in a global path. Other extensions, such as third-party/ent, only want to be used in the current project. Is it possible to change the setting to the GOPATH mode in goland, like the following
![gopath setting](https://user-images.githubusercontent.com/4726765/129381148-f5e3b884-4bc4-4a43-a697-49ddff56c803.png)

These are some immature suggestions of mine, and you should consider them as appropriate.

Thank you again for your excellent work！
