### ISSUE TITLE
Add support for envoyproxy/protoc-gen-validate

### ISSUE THREAD

**Issue by k1ng440** [devkanro/intellij-protobuf-plugin#42]
Thank you for writing this plugin, its mostly works except its throws error while using rules for envoyproxy/protoc-gen-validate

https://puu.sh/I3FGh/d1e225ec2d.png

thanks

**Comment by devkanro** [comment]
My syntax not support multi field name in options
Like this: 
```Protobuf
option (myOptions).field1.field2 = "";
```
Support this: 
```Protobuf
option (myOptions).field1 = { field2 : "" };
```

I will try to add it in next version.

**Comment by devkanro** [comment]
Fixed in 1.4.3

**Comment by devkanro** [comment]
I have fixed it in 1.4.3, could you delete your low rating review in Jetbrains Plugins?

https://plugins.jetbrains.com/plugin/16422-protobuf/reviews#review=58139

**Comment by k1ng440** [comment]
done. written a new review. thanks

**Comment by devkanro** [comment]
Thanks.
