### ISSUE TITLE
can not auto import

### ISSUE THREAD

**Issue by lin-mt** [devkanro/intellij-protobuf-plugin#46]
![image](https://user-images.githubusercontent.com/58337359/130000234-e6241d95-7ab8-4a2a-b748-be3375639890.png)

![image](https://user-images.githubusercontent.com/58337359/130000064-caa434e9-b78e-40ea-8d18-d7f0f75628a6.png)

plugin version: 1.4.2
idea version: 2021.2

**Comment by devkanro** [comment]
Need more information, please provide a simple project for it.

**Comment by lin-mt** [comment]
![image](https://user-images.githubusercontent.com/58337359/130002212-ad726024-6da5-4556-893a-975a1d6f3297.png)

![image](https://user-images.githubusercontent.com/58337359/130002258-2ae0da4d-166c-4c68-8c49-df584cd6bcdd.png)

[归档.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/7011477/default.zip)

**Comment by devkanro** [comment]
This plugin can auto-resolve protos in dependencies jar. You don't need config any settings.
Just mark your `src/proto` as resource dir in [maven pom](https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html), or move your protos to `src/resources`.

**Comment by devkanro** [comment]
Check the modified project.
No config, just add protobuf-java to dependency and mark `src/proto` as resource dir.
[demo.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/7011611/demo.zip)

**Comment by lin-mt** [comment]
> Check the modified project.
> No config, just add protobuf-java to dependency and mark `src/proto` as resource dir.
> [demo.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/7011611/demo.zip)

It works thx!
