### ISSUE TITLE
returns not prompt information

### ISSUE THREAD

**Issue by lin-mt** [devkanro/intellij-protobuf-plugin#47]
this is message
![image](https://user-images.githubusercontent.com/58337359/130188664-e77fcfe7-0231-41b8-b6d5-89ee0f5ddb66.png)

returns
![image](https://user-images.githubusercontent.com/58337359/130188750-4da2e2dc-bc74-4328-ac73-1fbcd567882d.png)

**Comment by devkanro** [comment]
I will try to add it in next version.

**Comment by devkanro** [comment]
Fixed in 1.4.3
