### ISSUE TITLE
proposal about more portable automatic import

### ISSUE THREAD

**Issue by CyJaySong** [devkanro/intellij-protobuf-plugin#50]
插件默认加载项目根目录的 proto 文件并且作用于全局，我希望可以提供关闭它的选项。
当我在编辑某个 proto 文件时，我希望可以自动加载同目录下的其他 proto 文件。而不是去`Perference -> Language and Framework -> Protobuf` 设置 path。因为如果在这里设置了 path, 它将作用于全局，以至于如果不同目录下的存在同名 proto文件时，引入将出现问题。我希望有个选项可以控制

The plugin load proto file of the project root directory and work globally. This is the default. I hope to provide the option to turn it off.

When I edit a proto file, I want to automatically load other proto file in the same directory. Instead of setting the path in `Perference -> Language and Framework -> Protobuf`. Because if set here, it will work globally, so that if there are proto files with the same name in different directories, there will be problems in importing. I need an option to control

**Comment by devkanro** [comment]
Fixed in [v1.4.4](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.4)
