### ISSUE TITLE
No suggestions of options

### ISSUE THREAD

**Issue by Kupstas** [devkanro/intellij-protobuf-plugin#51]
There are few examples how is looks like

<img width="383" alt="Screenshot 2021-09-04 at 09 37 31" src="https://user-images.githubusercontent.com/10007851/132085452-8b0543f5-c866-4166-b23a-c4c4c32c37e4.png">
<img width="242" alt="Screenshot 2021-09-04 at 09 37 21" src="https://user-images.githubusercontent.com/10007851/132085466-ee342aa7-e060-477a-a041-3868e6aae073.png">

**Comment by devkanro** [comment]
Need more information, your project language, build tool, your maven or gradle config.

Provide simple project is a best way.

Some issues maybe can help you.
- #46 
- #38 
- #4

**Comment by Kupstas** [comment]
The files compiles well but I have problems with plugin functionality. I'm using GoLand and WebStorm. Imports and type suggestion are working well but no `option` suggestion and they are highlighting red with error (for example) `Built-in option 'java_package' not found`

**Comment by devkanro** [comment]
The plugin will not provide the well-known protos, and the plugin will scan all depented libraries for the java project.

To make the plugin work with go project, you need to download google's well-known protos to a folder, and mark this folder as import root in `Settings` > `Language & Frameworks` > `Protobuf`.

If you can't find google's built-in protos, download it from [here](https://github.com/devkanro/intellij-protobuf-plugin/files/6775100/proto.zip).

See #4 for the details.

**Comment by Kupstas** [comment]
Yeah, I know about google built-in props and they included in project. But my error still presented

**Comment by devkanro** [comment]
Could you provide a simple project? I can't reproduce it.
