### ISSUE TITLE
Plugin is not compatible with Intellij IDEA 2021.3

### ISSUE THREAD

**Issue by eugeneatnezasa** [devkanro/intellij-protobuf-plugin#65]
Hi there!

Thank you for great job!

Would you mind to publish new version with support of 2021.3 just recently release? Because now I get warning before upgrade that plugin is not compatible with new version.

Thank you

**Comment by devkanro** [comment]
I will check it later.

**Comment by devkanro** [comment]
Check the release [v1.4.5](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.5).

Maybe it will be list in JetBrains Repository in 2 days.

**Comment by eugeneatnezasa** [comment]
Perfect, thanks a lot!
No more warnings!
