### ISSUE TITLE
多行字符串的支持

### ISSUE THREAD

**Issue by ppaanngggg** [devkanro/intellij-protobuf-plugin#68]
<img width="218" alt="image" src="https://user-images.githubusercontent.com/6350479/148157382-464256e3-9151-4516-950c-fbc3a532a69e.png">

目前这种情况下多行字符串会抛错并且干扰format，如果合并成一行太长了，麻烦可以支持一下

或者请问有什么替代做法吗

**Comment by devkanro** [comment]
确实能这么写，语法上比较好改，但是我有一些额外的逻辑，目前处理还比较粗糙，比如 http option 的 body 字段的跳转，这里会被标红

**Comment by devkanro** [comment]
在 commit a53a7f764d449a61648119ed8b9ef2e02bca7796 中实现了基本的功能，具体的细节后续再修补，等弄完就发版 1.4.6

**Comment by ppaanngggg** [comment]
确定proto是可以的，这样方便排版

感谢大佬 👍

**Comment by devkanro** [comment]
Fixed in [1.4.6](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.6)
