### ISSUE TITLE
自动补全需要忽略了reserved

### ISSUE THREAD

**Issue by ppaanngggg** [devkanro/intellij-protobuf-plugin#69]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6350479/149089319-052ef033-f493-4bbd-a2cf-72ec0acb82e6.png">

例如这个情况，inventory_descriptor自动补全为了13，但是前面有个reserved，应该自动补全为21更为合理

**Comment by devkanro** [comment]
在 commit ad0f7e28d7f0f34d5041556a3eaaba3e54ec5df5 中实现了，感觉两个功能，勉强可以凑一个版本出来

**Comment by devkanro** [comment]
Fixed in [1.4.6](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.6)

**Comment by ppaanngggg** [comment]
感谢，顺便问一下，你们工作中会从proto生成api文档吗，用什么工具生成的？

**Comment by devkanro** [comment]
proto 就是我们的 api 文档，我们会上传 proto 到版本控制工具里面，客户端和前端都根据特定版本的 proto 生成代码，代码上会有注释之类的，比看文档要方便。

另外针对 google.api.http 的 transcoding 场景，会自动生成 swagger。

参见：https://github.com/ButterCam/sisyphus/tree/master/starter/sisyphus-grpc-transcoding-starter/src/main/kotlin/com/bybutter/sisyphus/starter/grpc/transcoding/support/swagger
这部分目前还比较糙，看个意思就行了

**Comment by ppaanngggg** [comment]
我们现在在用 https://github.com/grpc-ecosystem/grpc-gateway 这里的 protoc-gen-openapiv2

但这个东西现在对java不太友好，没法直接gradle装个插件用

**Comment by devkanro** [comment]
现在 proto 和 grpc 的技术栈就是很松散，啥功能都有，缺一些能把这些工具结合在一起的东西。
所以我们这边就是自己做了一些框架开发，就有了 [ButterCam/sisyphus](https://github.com/ButterCam/sisyphus)。
不过我们主要是用 kotlin，java 用的少，所以基本上框架也就我们自己用
