### ISSUE TITLE
嵌套的message没有自动补全

### ISSUE THREAD

**Issue by ppaanngggg** [devkanro/intellij-protobuf-plugin#70]
版本：1.4.6

<img width="154" alt="image" src="https://user-images.githubusercontent.com/6350479/149700058-671bc596-344b-42cc-8bb1-350fae56143e.png">

例如这个场景，AuditElementContent里面还有Text等多个message定义，但是按下`.`之后没有弹出嵌套的message补全

**Comment by devkanro** [comment]
没有复现，你看看是不是没有 import AuditElementContent

**Comment by ppaanngggg** [comment]
> import AuditElementContent

这个确定import了

**Comment by ppaanngggg** [comment]
<img width="101" alt="image" src="https://user-images.githubusercontent.com/6350479/149701008-3b93c109-7b2d-4076-8c36-3fc3835038d9.png">
会不会是跨了文件夹的原因

**Comment by devkanro** [comment]
能看看你是怎么 import 的吗

**Comment by devkanro** [comment]
另外你是啥项目？Java 还是 Go？

**Comment by ppaanngggg** [comment]
> 另外你是啥项目？Java 还是 Go？

java项目

在`advertise/business_card.proto`里面import

<img width="236" alt="image" src="https://user-images.githubusercontent.com/6350479/149701256-94f8fb4c-74bb-462e-ba10-592bcc7c9ac6.png">

**Comment by devkanro** [comment]
那应该没啥问题，Java 项目的话，也不需要配置啥
第一层的 message 能补全吗？

**Comment by ppaanngggg** [comment]
> 第一层的 message 能补全吗？

第一层可以，就是第二层不行

那个AuditElementContent长这样

<img width="129" alt="image" src="https://user-images.githubusercontent.com/6350479/149701566-d6afd351-224d-48a6-b149-c20c1e42d52b.png">

**Comment by devkanro** [comment]
复现了，等我修一下吧

**Comment by devkanro** [comment]
在 ff9d0afcb77639c6e8497e6625afd6d9204f2e5b 里面修复了，但是一行代码不是很想发新版啊

**Comment by ppaanngggg** [comment]
> 在 ff9d0afcb77639c6e8497e6625afd6d9204f2e5b 里面修复了，但是一行代码不是很想发新版啊

重大feature，发一个吧
