### ISSUE TITLE
multiple choices

### ISSUE THREAD

**Issue by EvGeniyLell** [devkanro/intellij-protobuf-plugin#72]
The plugin detects incorrect `multiple choices` 
for example app has the next structure
```
app
-plugin_a
--protobuf
---features_dto.proto
---exampe.proto {
  syntax = "proto3";
  package com.app.plugin_a;
  import "protobuf/features_dto.proto";
  message Test {
    FeatureDto feature = 1; // <- multiple choices error
  }
}
---*other*.proto
---*other*.proto
-plugin_b
--protobuf
---features_dto.proto
---exampe.proto {
  syntax = "proto3";
  package com.app.plugin_b;
  import "protobuf/features_dto.proto";
  message Test {
    FeatureDto feature = 1; // <- multiple choices error
  }
}
---*other*.proto
---*other*.proto
```
then when I, in each plugin, in some other `protobuf/*.proto` try to `import "protobuf/features_dto.proto"` i have the error `multiple choices`
and marked red `messages` and/or `enums` from `protobuf/features_dto.proto`
i try to select one of the `multiple choices` options, but i still see the error.
i think this behavior is incorrect, because the different directories.

**Comment by devkanro** [comment]
What is kind of your project? Go project or Java?

**Comment by devkanro** [comment]
Have you mark the `plugin_a` and `plugin_b` dir as **common** protobuf root dir?
Give me your protobuf plugin setting page?

**Comment by EvGeniyLell** [comment]
the `flutter` app for `android` and `iOS`
I don't have any special setting, using by default
<img width="999" alt="Screenshot 2022-01-24 at 12 39 12" src="https://user-images.githubusercontent.com/1710383/150768064-30526de3-7ca6-4170-b179-a70d604a9b9f.png">
<img width="991" alt="Screenshot 2022-01-24 at 12 41 19" src="https://user-images.githubusercontent.com/1710383/150768324-de9b2b48-7154-4194-b5da-e306d87ee68d.png">

**Comment by devkanro** [comment]
Can you give me a sample project? I have no idea for it, need more test.

**Comment by devkanro** [comment]
> Can you give me a sample project?

Any update?

**Comment by EvGeniyLell** [comment]
https://github.com/EvGeniyLell/sample_multiple_choices

**Comment by devkanro** [comment]
I got some imported files is not found with no config just open the flutter project.

Have you config anything the protobuf dir? like `mark dir as ...` etc.

![image](https://user-images.githubusercontent.com/9367842/151287275-6959c506-832e-450d-98f8-dce10987a72d.png)

**Comment by devkanro** [comment]
It back to normal when I config plugin_a and plugin_b as protobuf root

![image](https://user-images.githubusercontent.com/9367842/151287847-2c37c6f3-56d7-47d4-b691-4282a6e6efc9.png)

![image](https://user-images.githubusercontent.com/9367842/151287875-67596cae-bdd1-4581-aed9-ab74269fec08.png)

**Comment by EvGeniyLell** [comment]
then check in plugin b, it still has the error

**Comment by EvGeniyLell** [comment]
it looks like in IntelliJ on Flutter this `Protobuf` plugin puts all `*.proto` to one namespace. it can be impove?

**Comment by devkanro** [comment]
Ummm...It works for me, both of plugin a and b.

![image](https://user-images.githubusercontent.com/9367842/1533
![image](https://user-images.githubusercontent.com/9367842/153362633-812dbddc-3ada-4fcd-aa00-c44d65279309.png)
62606-557863b8-41b7-4bb8-aa5d-cb29fba3537c.png)

**Comment by devkanro** [comment]
Close it because no more response. If you have any update please reopen it.
