### ISSUE TITLE
python和go的文件跳转到protobuf？

### ISSUE THREAD

**Issue by ppaanngggg** [devkanro/intellij-protobuf-plugin#77]
目前好像不支持python和go的代码中点击生成的类跳转到protobuf文件的对应位置？

也可能是我配置不对，请问下具体情况是怎么样的

**Comment by devkanro** [comment]
目前不支持生成的代码跳转到 protobuf 文件里面，我自己不太需要这个功能就暂时没打算加。

原生插件支持这个我是知道的，但是用起来挺混乱的，go 和 python 生成的代码我不太清楚，对一个字段而言 java 的代码会生成出来 getter setter has 和 clear 方法，点任何一个都会跳转到 protobuf 字段，感觉挺奇怪的。

这个功能还没想好具体的该怎么做，所以一直都没做。

另外是，插件支持一部分的上面跳转的功能，主要是在 rpc 和 service 相应实现的代码提供一个行前的一个小图标，可以跳转到 protobuf 定义。

**Comment by devkanro** [comment]
具体对于 Go 语言的特性支持，可以看 
- #37

另外对于 python 语法不熟悉，暂时没有打算对 python 提供更多的支持，欢迎提供 PR 或者开发子插件

**Comment by ppaanngggg** [comment]
好的，我观察官方的插件好像主要是根据注释里的tag来的

**Comment by devkanro** [comment]
说到这个，官方插件最近下面正好有用户投诉为啥点进去就直接到 protobuf，这个功能我用的时候也挺疑惑的。

![image](https://user-images.githubusercontent.com/9367842/157413126-09e725c7-2515-4bf9-bbe3-3740e979cb49.png)

**Comment by ppaanngggg** [comment]
> 说到这个，官方插件最近下面正好有用户投诉为啥点进去就直接到 protobuf，这个功能我用的时候也挺疑惑的。
> 
> ![image](https://user-images.githubusercontent.com/9367842/157413126-09e725c7-2515-4bf9-bbe3-3740e979cb49.png)

哈哈哈，这是他做的不好的地方，哪天我真的想去看生成的代码的时候切过去很麻烦。

但是java和python生成的代码没法看，一般也不会去看，go和kotlin的可以看看。

但我们现在一般把proto当api文档用，所以跳转到proto最方便，没跳转到代码的实际需求。
