### ISSUE TITLE
导入问题，go_packag声明找不到

### ISSUE THREAD

**Issue by yexua** [devkanro/intellij-protobuf-plugin#79]
GoLand 2021.3.3
Build #GO-213.6777.51, built on January 27, 2022
For non-commercial open source development only.
Runtime version: 11.0.13+7-b1751.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7

我更新Goland至版本21.3，之后下载了该插件的1.4.8版本，并禁用官方的Protobuf和Grpc插件。

我看了之前的issues，还是没有解决
<img width="526" alt="image" src="https://user-images.githubusercontent.com/44164267/159653052-be028bd2-1668-4593-ab4e-9408b165bbd2.png">

目前import的智能导入提示也没有了，google的proto也无法导入。
<img width="783" alt="image" src="https://user-images.githubusercontent.com/44164267/159653459-abf374cb-68f2-4216-9e32-394b4e5151b8.png">
我手动设置了目录，但还是没有效果

**Comment by devkanro** [comment]
1.4.8 版本的插件并未提供 Wellknown Protobuf 类型，在 Go 项目中需要自助配置，你可以在[这里](https://github.com/devkanro/intellij-protobuf-plugin/files/6775100/proto.zip)下载到所有 Google 内置的 Protobuf 文件。将这些文件解压，并在配置中加入解压后的目录就可以识别了。

另外，在 1.5.0 版本之后，插件将会自带所有的 Wellknown Protobuf，无需配置，1.5.0 目前仍然处于 EAP 阶段，你可以在 [Github Release](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.5.0-EAP) 或 [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/16422-protobuf/versions/EAP/163088) 中下载，预计会在本周发布 1.5.0 正式版。

**Comment by yexua** [comment]
感谢
