### ISSUE TITLE
gradle build fail

### ISSUE THREAD

**Issue by lin-mt** [devkanro/intellij-protobuf-plugin#82]
想加一个命名风格的配置，但是构建失败了～下载了 [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) 执行了publishToMavenLocal 成功了，但是 [intellij-protobuf-plugin](https://github.com/devkanro/intellij-protobuf-plugin) 还是构建失败，是少了什么 kotlin 的配置吗（本人java开发）

A problem occurred configuring root project 'idea-protobuf-plugin'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0.
     Required by:
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:1.4.0
      > No matching variant of org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4' but:
          - Variant 'apiElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'runtimeElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by lin-mt** [comment]
jdk 设置的 11

**Comment by devkanro** [comment]
我感觉还是 JDK 的设置问题，你看看 设置 -> Build Tools -> Gradle 的 Gradle JVM 是不是也是 JDK 11

**Comment by lin-mt** [comment]
> 我感觉还是 JDK 的设置问题，你看看 设置 -> Build Tools -> Gradle 的 Gradle JVM 是不是也是 JDK 11

是这个问题，可以了

**Comment by devkanro** [comment]
另外虽然 Java 也能写，但是 PR 只接受 Kotlin 代码，建议用 Kotlin 写
