### ISSUE TITLE
部分文件没有找到

### ISSUE THREAD

**Issue by lin-mt** [devkanro/intellij-protobuf-plugin#83]
![image](https://user-images.githubusercontent.com/58337359/160367559-e2efb9c7-91e6-4cb1-afc0-572fe6978a40.png)
是不是少提交了什么文件？

**Comment by devkanro** [comment]
执行一下
![image](https://user-images.githubusercontent.com/9367842/160368098-f330b3b6-7777-41df-8e26-f656ddabbb26.png)

或者是
直接执行一下 build 什么的
