### ISSUE TITLE
部分包装类型没有提示

### ISSUE THREAD

**Issue by lin-mt** [devkanro/intellij-protobuf-plugin#89]
![image](https://user-images.githubusercontent.com/58337359/161189743-792983eb-4dd9-4943-9001-9cfc02c1a729.png)

**Comment by lin-mt** [comment]
idea 版本：2021.3.3
plugin：1.5.0

**Comment by devkanro** [comment]
能给一个实例工程吗，没有复现

**Comment by lin-mt** [comment]
> 能给一个实例工程吗，没有复现

![image](https://user-images.githubusercontent.com/58337359/161202120-e821eacd-eca2-42c1-b635-7a4da48d28c9.png)
新建一个 sprongboot 项目就能复现了

**Comment by lin-mt** [comment]
已经离职了，可能是公司的 idea 我设置的有问题吧，先 close 了哈
