### ISSUE TITLE
PascalCase warning

### ISSUE THREAD

**Issue by ppaanngggg** [devkanro/intellij-protobuf-plugin#93]
![image](https://user-images.githubusercontent.com/6350479/162134115-347571e0-890f-4ffc-80a3-622fad93ac06.png)

现在对message或者method里面有全大写所写会报warning `Message name should be PascalCase`。但我觉得这个缩写改成驼峰也不合适，感觉这个warning是不是可以让步一下，这种情况不需要warning？或者降低级别，或者提供inception关掉的方式？

**Comment by devkanro** [comment]
- #45 
重复了，inception 重构起来是个大工程...

**Comment by ppaanngggg** [comment]
oh，好的，那我这边close掉吧，加油大佬
