### ISSUE TITLE
Buf UI shows 

### ISSUE THREAD

**Issue by AlmogBaku** [devkanro/intellij-protobuf-plugin#94]
<img width="563" alt="Screen Shot 2022-04-10 at 14 44 28" src="https://user-images.githubusercontent.com/98982/162616495-15d87bda-84bd-484c-9fc7-5a039933a643.png">
Buf UI shows weird text... It doesn't seems right ;-)

I'm using GoLand 2021.3.4 (Build #GO-213.7172.22, built on March 15, 2022)

**Comment by devkanro** [comment]
This is a known bug, but only recurrent with 2022.1 or higher in my . Anyway, I will fix it later.

**Comment by devkanro** [comment]
Ummm...Recurrent with IU-2021.3.3, maybe also with GoLand 2021.3.4

**Comment by devkanro** [comment]
Fixed in 1.5.11
