### ISSUE TITLE
在goland中打开一个新的项目,每次都会卡好久.

### ISSUE THREAD

**Issue by tangqiu0205** [devkanro/intellij-protobuf-plugin#99]
这个进度条大概会卡一分钟, 如果禁用本插件,打开项目就不会卡了.
goland: 2022.1

![QQ图片20220503232341](https://user-images.githubusercontent.com/37826977/166483895-1d4f752c-00c5-4f8e-ad11-3eb91f932189.jpg)

**Comment by devkanro** [comment]
这个操作会从所有的 go 文件里面找到 proto 生成的 go 文件，然后从里面的 descriptor 字段反编译出来 proto 以供使用。

如果 go 文件（包含引用的库）比较多，确实可能会导致这样的问题。

我在考虑是不是加一个选项关闭这个功能，感觉也没啥其他的好办法了

**Comment by devkanro** [comment]
在预计发版的 1.6.0 中提供了一个设置来禁用自动反编译功能。
<img width="445" alt="截屏2022-06-08 下午4 10 53" src="https://user-images.githubusercontent.com/9367842/172566243-1f0ca8e5-bf69-47cf-a1f5-d7872f3a1e29.png">
把这个选项取消就可以了。

**Comment by tangqiu0205** [comment]
好的.

**Comment by devkanro** [comment]
Fixed by release [v1.6.0](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.6.0)

**Comment by tangqiu0205** [comment]
设置界面打不开.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/37826977/173024456-bf17c9b4-3bcc-49bd-837b-e2b673adeb28.png">

**Comment by devkanro** [comment]
请针对这个问题创建一个新的 issue
